apiVersion: v2
name: datamigratie
description: A Helm chart for the Datamigratie Component

type: application

# Chart version 
version: 0.0.0
appVersion: 0.0.0

dependencies:
  - name: postgresql
    version: 12.5.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled